### ISSUE TITLE
Agregar un Header a todas las secciones

### ISSUE THREAD

**Issue by lealskrs** [lealskrs/cursoprogramacion#3]

**Comment by gabriela-zapata** [comment]
@lealskrs Probando comentario

**Comment by lealskrs** [comment]
![image](https://user-images.githubusercontent.com/19808759/91181210-0a0d3080-e6bf-11ea-8b45-7504f013c3a6.png)
@gabriela-zapata Esta imagen de arriba muestra como tendría que ser mas o menos el estilo del header. En lugar de "LOGOBAKERY" tendria que tener el nombre de la pagina que de momento podria ser solo CLASES DE PROGRAMACION o algo por el estilo.
Luego irian todas las secciones que fuimos pensando, y al final el boton de "contact" esta bien dejarlo
